#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
generate_manifest.py — thin orchestrator for the marketplace generator.

Phases (post scope-down, issue #18 — Claude Code is the only platform):
  1.  Individual construct plugins: emit one _generated/<prefix>-<name>/ per source
  5.  Top-level marketplace.json: write from in-memory entries (decision #17)
  7.  _generated/CATALOG_AND_INSTALLATION_INSTRUCTIONS.md: the generated catalog -
      every plugin, every install/removal path, invocation tables

(Phase numbering is kept sparse deliberately — the retired phases 1.5/3/4/4.5/
5.5/6 emitted per-platform manifests and mirrors for the removed platforms;
see git history and issues #28–#36 for what they were.)

Usage:
  uv run scripts/generate_manifest.py          # write everything
  uv run scripts/generate_manifest.py --check  # exit non-zero if output differs
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

# Add scripts/ to sys.path so sibling modules resolve correctly
sys.path.insert(0, str(Path(__file__).resolve().parent))

from constructs import CONSTRUCTS
from platforms import ClaudeCodePlatform
from utils import (
    GENERATED,
    MARKETPLACE_JSON,
    REPO_ROOT,
    _marketplace_author,
    _marketplace_description,
    _marketplace_name,
    _marketplace_version,
    _to_json,
    scan_source_dir,
    write_plugin_json,
)


def _make_marketplace_entry(
    plugin_json: dict, plugin_dir: Path, category: str
) -> dict:
    """Build a marketplace.json plugin entry from an in-memory plugin.json dict.

    The marketplace entry ``name`` is the install-time identifier (what the
    operator types after ``claude plugin install``). It is unique per plugin
    and is derived here from ``plugin_dir.name`` (set in Phase 1 as
    ``<construct.prefix>-<source-dir-name>``, e.g. ``skill-example``).

    Post-2026-05-28 (multi-instance-capable refactor): ``plugin_json["name"]``
    is the **plugin's slash namespace** (``<brand>-<construct.prefix>-<source-
    dir-name>``, e.g. ``dgxsparklabs-skill-example``). It is also unique per
    plugin, and the two fields differ only in the brand prefix.

    An earlier short-lived attempt (Path A, ``d641f92``, 2026-05-27) used a
    SHARED ``<brand>-<construct.category>`` name across all plugins of one
    construct type, with the intent of grouping multi-instance components
    under a single slash namespace. Path A was reverted on 2026-05-28 after
    ``claude plugin details <shared-namespace>`` collapsed to a single first-
    installed-wins view of components. The revert rationale is preserved on the
    project-memory branch (multi-instance PLAN).
    """
    return {
        "name": plugin_dir.name,
        "source": f"./{plugin_dir.relative_to(REPO_ROOT).as_posix()}",
        "description": plugin_json["description"],
        "version": plugin_json["version"],
        "author": plugin_json["author"],
        "category": category,
    }


def _write_marketplace_json(entries: list[dict]) -> None:
    """Write the top-level marketplace.json from in-memory entries.

    Sorted by category then name for deterministic diffs.
    """
    entries.sort(key=lambda e: (e["category"], e["name"]))
    manifest = {
        "name": _marketplace_name(),
        "owner": _marketplace_author(),
        "description": _marketplace_description(),
        "plugins": entries,
    }
    MARKETPLACE_JSON.parent.mkdir(parents=True, exist_ok=True)
    MARKETPLACE_JSON.write_text(_to_json(manifest), encoding="utf-8", newline="")


def _write_catalog(entries: list[dict]) -> None:
    """Emit _generated/CATALOG_AND_INSTALLATION_INSTRUCTIONS.md.

    The generated, drift-checked catalog: every published plugin, grouped by
    construct, with EVERY installation path spelled out per platform (plugin
    install + direct copy, each with its deletion) and the invocation table -
    all rendered with this marketplace's own identity so a fork's catalog is
    copy-pasteable as-is. Heading contract: ## construct / ### plugin /
    #### platform / ##### method / ###### deletion.
    """
    from collections import Counter

    from utils import _marketplace_display_name

    cats = Counter(e["category"] for e in entries)
    lines = [
        f"# {_marketplace_display_name()} - catalog & installation instructions",
        "",
        "_Generated by `scripts/generate_manifest.py` - do not edit by hand. This is "
        "the authoritative list of published plugins and every supported way to "
        "install, remove, and invoke each one._",
        "",
        f"**{len(entries)} plugin entries**: "
        + ", ".join(f"{count} {cat}" for cat, count in sorted(cats.items())),
        "",
        "## Table of contents",
        "",
    ]
    def _slug(text: str) -> str:
        # GitHub heading anchor: lowercase, spaces to hyphens (our headings are
        # already kebab-case names, so this stays trivially correct).
        return text.lower().replace(" ", "-")
    for cat in sorted(cats):
        cat_heading = f"{cat}s" if not cat.endswith("s") else cat
        lines.append(f"- [{cat_heading}](#{_slug(cat_heading)})")
        for e in sorted((x for x in entries if x["category"] == cat), key=lambda x: x["name"]):
            lines.append(f"  - [{e['name']}](#{_slug(e['name'])})")
    lines.append("")
    by_prefix = {c.prefix: c for c in CONSTRUCTS.values()}
    for cat in sorted(cats):
        lines.append(f"## {cat}s" if not cat.endswith("s") else f"## {cat}")
        lines.append("")
        for e in sorted((x for x in entries if x["category"] == cat), key=lambda x: x["name"]):
            construct = next((c for pfx, c in by_prefix.items() if e["name"].startswith(pfx + "-")), None)
            if construct is None or not hasattr(construct, "catalog_section"):
                lines.append(f"### {e['name']}")
                lines.append("")
                lines.append("[↑ Table of contents](#table-of-contents)")
                lines.append("")
                lines.append(e["description"])
                lines.append("")
                continue
            src_name = e["name"].removeprefix(construct.prefix + "-")
            section = construct.catalog_section(src_name)
            heading = f"### {e['name']}"
            section = section.replace(
                heading, heading + chr(10) + chr(10) + "[↑ Table of contents](#table-of-contents)", 1
            )
            lines.append(section)
    (GENERATED.parent / "CATALOG_AND_INSTALLATION_INSTRUCTIONS.md").write_text(
        chr(10).join(lines), encoding="utf-8", newline=""
    )



def main() -> None:
    marketplace_entries: list[dict] = []

    # Count of individual (non-bundle) plugins for the summary line.
    individual_plugin_count = 0

    # Constructs that emit a Claude plugin (== entry in
    # ``.claude-plugin/marketplace.json``). RuleConstruct is intentionally
    # absent per F8: rules are a Claude memory feature, not a plugin
    # component. See ClaudeCodePlatform.supports docstring in platforms.py
    # and the project-memory branch (claude-qa RESEARCH.md, F8).
    claude_supports = ClaudeCodePlatform.supports

    # Clear and recreate _generated/ (clean slate each run)
    if GENERATED.exists():
        shutil.rmtree(GENERATED)
    GENERATED.mkdir(parents=True)

    # ── Phase 1: Individual construct plugins ──────────────────────────────────
    # The marketplace entry is added when the construct is in
    # ClaudeCodePlatform.supports.
    for construct in CONSTRUCTS.values():
        is_claude_plugin = type(construct) in claude_supports
        for name in scan_source_dir(construct.source_directory):
            plugin_dir = GENERATED / f"{construct.prefix}-{name}"
            plugin_dir.mkdir(parents=True, exist_ok=True)
            construct.emit(name, plugin_dir)
            if is_claude_plugin:
                plugin_json = construct.build_plugin_json(name)
                marketplace_entries.append(
                    _make_marketplace_entry(plugin_json, plugin_dir, construct.category)
                )
            individual_plugin_count += 1

    # ── Phase 5: Top-level marketplace.json (from in-memory entries) ──────────
    _write_marketplace_json(marketplace_entries)

    # ── Phase 7: the generated catalog & installation doc (drift-checked) ──────
    _write_catalog(marketplace_entries)

    # Summary
    from collections import Counter
    cats = Counter(e["category"] for e in marketplace_entries)
    print(f"Generated {len(marketplace_entries)} plugin entries in marketplace.json")
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")
    print(f"  {individual_plugin_count} individual plugins")


def _check_drift() -> int:
    """Snapshot current outputs, regenerate, diff. Return 0 if identical, 1 if drift.

    On drift the pre-check tree is RESTORED before returning, so --check is
    read-only from the caller's point of view and deterministic across runs.
    (Before this fix the check regenerated in place and left the new tree on
    disk, so a failing check silently "fixed" the drift and a rerun passed —
    three independent newcomer walkthroughs hit that fail-once-then-pass trap.)
    """

    def snapshot_tree(roots: list[Path]) -> dict[str, bytes]:
        out: dict[str, bytes] = {}
        for root in roots:
            if not root.exists():
                continue
            if root.is_file():
                # Individual file targets (the generated catalog doc).
                # rglob("*") yields nothing for a file, so these must be read directly.
                out[str(root.relative_to(REPO_ROOT))] = root.read_bytes()
                continue
            for p in sorted(root.rglob("*")):
                if p.is_file():
                    out[str(p.relative_to(REPO_ROOT))] = p.read_bytes()
        return out

    # Root-level generated files (no mirror dirs remain post scope-down)
    root_generated = [
        REPO_ROOT / "_generated" / "CATALOG_AND_INSTALLATION_INSTRUCTIONS.md",  # Phase 7
    ]
    targets = [GENERATED, MARKETPLACE_JSON.parent] + root_generated

    before = snapshot_tree(targets)
    main()
    after = snapshot_tree(targets)

    if before == after:
        print("OK: generated content matches committed content.")
        return 0

    missing = sorted(set(before) - set(after))
    added = sorted(set(after) - set(before))
    changed = sorted(p for p in (set(before) & set(after)) if before[p] != after[p])

    # Restore the pre-check tree: delete files the regen added, rewrite
    # every file that existed before. Directories emptied by the deletes are
    # pruned so the tree is byte-identical to the pre-check state.
    for rel in added:
        (REPO_ROOT / rel).unlink(missing_ok=True)
    for rel, data in before.items():
        p = REPO_ROOT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
    for root in targets:
        if root.is_dir():
            for d in sorted(root.rglob("*"), reverse=True):
                if d.is_dir() and not any(d.iterdir()):
                    d.rmdir()

    print("DRIFT detected. Run `uv run scripts/generate_manifest.py` and commit the result.")
    print("(working tree restored to its pre-check state)")
    for p in missing:
        print(f"  removed:  {p}")
    for p in added:
        print(f"  added:    {p}")
    for p in changed:
        print(f"  changed:  {p}")
    return 1


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(_check_drift())
    main()
