#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
generate_manifest.py — thin orchestrator for the marketplace generator.

Phases (post scope-down, issue #18 — Claude Code is the only platform):
  1.  Individual construct plugins: emit one _generated/<prefix>-<name>/ per source
  5.  Top-level marketplace.json: write from in-memory entries (decision #17)
  7.  _generated/CATALOG_AND_INSTALLATION_INSTRUCTIONS.md: the generated catalog -
      every plugin, every install/removal path, invocation tables
  8.  _generated/LINTING_RULES.md: the generated lint-rule list, rendered
      from the scripts/lint_rules/ registry (construct-grouped, with failure
      examples captured by executing each rule's counterexample)

(Phase numbering is kept sparse deliberately — the retired phases 1.5/3/4/4.5/
5.5/6 emitted per-platform manifests and mirrors for the removed platforms;
see git history and issues #28–#36 for what they were.)

Usage:
  uv run scripts/generate_manifest.py          # write everything
  uv run scripts/generate_manifest.py --check  # exit non-zero if output differs
"""

from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

# Add scripts/ to sys.path so sibling modules resolve correctly
sys.path.insert(0, str(Path(__file__).resolve().parent))

from constructs import CONSTRUCTS
from platforms import PLATFORMS
from utils import (
    GENERATED,
    REPO_ROOT,
    _to_json,
    scan_source_dir,
    write_plugin_json,
)


def _make_marketplace_entry(
    plugin_json: dict, plugin_dir: Path, category: str
) -> dict:
    """Build a marketplace.json plugin entry from an in-memory plugin.json dict.

    The marketplace entry ``name`` is the install-time identifier (what the
    operator types after ``claude plugin install``). It is unique per plugin
    and is derived here from ``plugin_dir.name`` (set in Phase 1 as
    ``<construct.prefix>-<source-dir-name>``, e.g. ``skill-example``).

    Post-2026-05-28 (multi-instance-capable refactor): ``plugin_json["name"]``
    is the **plugin's slash namespace** (``<brand>-<construct.prefix>-<source-
    dir-name>``, e.g. ``dgxsparklabs-skill-example``). It is also unique per
    plugin, and the two fields differ only in the brand prefix.

    An earlier short-lived attempt (Path A, ``d641f92``, 2026-05-27) used a
    SHARED ``<brand>-<construct.category>`` name across all plugins of one
    construct type, with the intent of grouping multi-instance components
    under a single slash namespace. Path A was reverted on 2026-05-28 after
    ``claude plugin details <shared-namespace>`` collapsed to a single first-
    installed-wins view of components. The revert rationale is preserved on the
    project-memory branch (multi-instance PLAN).
    """
    return {
        "name": plugin_dir.name,
        "source": f"./{plugin_dir.relative_to(REPO_ROOT).as_posix()}",
        "description": plugin_json["description"],
        "version": plugin_json["version"],
        "author": plugin_json["author"],
        "category": category,
    }


def _entries_for_platform(platform, emitted: list[tuple]) -> list[dict]:
    """Marketplace entries for the plugins ``platform`` supports.

    ``emitted`` is the Phase-1 list of (construct, plugin_dir, plugin_json).
    """
    entries: list[dict] = []
    for construct, plugin_dir, plugin_json in emitted:
        if type(construct) in platform.supports and plugin_json is not None:
            entries.append(
                _make_marketplace_entry(plugin_json, plugin_dir, construct.category)
            )
    return entries


def _write_marketplace_json(manifest: dict, path: Path) -> None:
    """Write a prebuilt top-level marketplace.json dict to ``path``.

    ``newline=""`` preserves the LF endings from ``_to_json`` on Windows so the
    byte-wise drift check stays green.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_to_json(manifest), encoding="utf-8", newline="")


def _write_catalog(entries: list[dict]) -> None:
    """Emit _generated/CATALOG_AND_INSTALLATION_INSTRUCTIONS.md.

    The generated, drift-checked catalog: every published plugin, grouped by
    construct, with EVERY installation path spelled out per platform (plugin
    install + direct copy, each with its deletion) and the invocation table -
    all rendered with this marketplace's own identity so a fork's catalog is
    copy-pasteable as-is. Heading contract: ## construct / ### plugin /
    #### platform / ##### method / ###### deletion.
    """
    from collections import Counter

    from utils import _marketplace_display_name

    cats = Counter(e["category"] for e in entries)
    lines = [
        f"# {_marketplace_display_name()} - catalog & installation instructions",
        "",
        "_Generated by `scripts/generate_manifest.py` - do not edit by hand. This is "
        "the authoritative list of published plugins and every supported way to "
        "install, remove, and invoke each one._",
        "",
        f"**{len(entries)} plugin entries**: "
        + ", ".join(f"{count} {cat}" for cat, count in sorted(cats.items())),
        "",
        "## Table of contents",
        "",
    ]
    def _slug(text: str) -> str:
        # GitHub heading anchor: lowercase, spaces to hyphens (our headings are
        # already kebab-case names, so this stays trivially correct).
        return text.lower().replace(" ", "-")
    for cat in sorted(cats):
        cat_heading = f"{cat}s" if not cat.endswith("s") else cat
        lines.append(f"- [{cat_heading}](#{_slug(cat_heading)})")
        for e in sorted((x for x in entries if x["category"] == cat), key=lambda x: x["name"]):
            lines.append(f"  - [{e['name']}](#{_slug(e['name'])})")
    lines.append("")
    by_prefix = {c.prefix: c for c in CONSTRUCTS.values()}
    for cat in sorted(cats):
        lines.append(f"## {cat}s" if not cat.endswith("s") else f"## {cat}")
        lines.append("")
        for e in sorted((x for x in entries if x["category"] == cat), key=lambda x: x["name"]):
            construct = next((c for pfx, c in by_prefix.items() if e["name"].startswith(pfx + "-")), None)
            if construct is None or not hasattr(construct, "catalog_section"):
                lines.append(f"### {e['name']}")
                lines.append("")
                lines.append("[↑ Table of contents](#table-of-contents)")
                lines.append("")
                lines.append(e["description"])
                lines.append("")
                continue
            src_name = e["name"].removeprefix(construct.prefix + "-")
            section = construct.catalog_section(src_name)
            heading = f"### {e['name']}"
            section = section.replace(
                heading, heading + chr(10) + chr(10) + "[↑ Table of contents](#table-of-contents)", 1
            )
            lines.append(section)
    (GENERATED.parent / "CATALOG_AND_INSTALLATION_INSTRUCTIONS.md").write_text(
        chr(10).join(lines), encoding="utf-8", newline=""
    )



def _verified_example(rule) -> str:
    """Run a rule's counterexample and capture the message the driver emits.

    The example in the published document is therefore never typed by hand: it
    is what the code actually produced, at generation time. Paths are rendered
    relative to the throwaway fixture root so the output is deterministic and
    the drift gate stays meaningful.
    """
    import tempfile

    from lint import run

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        rule.counterexample(root)
        for finding in run(root, {rule.stage}):
            if finding.rule.id == rule.id:
                message = finding.message(relative_to=root)
                # A message that carries the throwaway fixture path would differ
                # per run/machine and turn the drift gate into noise. Check all
                # three spellings a Windows path can wear (raw tmp, str(Path),
                # as_posix) and fail loudly rather than emit an unstable doc.
                leaks = {tmp, str(root), root.as_posix()}
                if any(leak in message for leak in leaks):
                    raise ValueError(
                        f"rule {rule.id}: its message embeds an absolute path "
                        f"({message!r}). Violation details must name a location, "
                        f"not path it, or the generated document is unstable."
                    )
                return message
    raise ValueError(
        f"rule {rule.id}: its counterexample did not provoke it. A rule that "
        f"cannot be triggered must not be published as enforced."
    )


def _write_lint_rules_doc() -> None:
    """Emit _generated/LINTING_RULES.md from the lint-rule registry.

    Rendered from the SAME objects the lint driver executes
    (``scripts/lint_rules/``), so the published list cannot describe a rule
    that does not run, omit one that does, or misstate a severity. The example
    failure under each rule is captured by executing that rule's mandatory
    counterexample through the real driver.

    Grouped construct-first — a contributor reads "the rules that apply to
    me". Heading contract: ``##`` construct group / ``###`` rule id, each
    heading immediately followed by the back-to-contents link (repo
    convention, see AGENTS.md).
    """
    from constructs import CONSTRUCTS
    from lint_rules import LINT_RULES

    def _slug(text: str) -> str:
        out = []
        for ch in text.lower():
            if ch.isalnum() or ch == "-":
                out.append(ch)
            elif ch == " ":
                out.append("-")
        return "".join(out)

    def _title(construct: str) -> str:
        return construct.capitalize() + "s"

    BACK = "[\u2191 Table of contents](#table-of-contents)"

    universal = [r for r in LINT_RULES if "*" in r.constructs]
    groups: list[tuple[str, list]] = [("Rules for every construct", universal)]
    for key in CONSTRUCTS:
        mine = [
            r for r in LINT_RULES
            if "*" not in r.constructs and key in r.constructs
        ]
        if mine:
            groups.append((_title(key), mine))

    # No silent drops: a construct-specific rule naming only unregistered
    # constructs would be enforced-nowhere AND documented-nowhere.
    rendered = {r.id for _, rs in groups for r in rs}
    dropped = sorted(r.id for r in LINT_RULES if r.id not in rendered)
    if dropped:
        raise ValueError(
            f"rules {dropped} name no registered construct; they would vanish "
            f"from LINTING_RULES.md while still being declared"
        )

    L: list[str] = []
    A = L.append
    A("# Linting rules")
    A("")
    A("_Generated by `scripts/generate_manifest.py` from the registry in "
      "`scripts/lint_rules/` - do not edit by hand. Each rule below is the "
      "same object the linter executes, and every example message was "
      "captured by actually running that rule against input built to "
      "break it._")
    A("")
    A(f"**{len(LINT_RULES)} rules.** Every failure message quotes its rule id, "
      "so the id in an error is the id to look up here. `error` blocks "
      "publishing; `warning` is advisory.")
    A("")
    A("## Table of contents")
    A("")
    for title, rs in groups:
        A(f"- [{title}](#{_slug(title)})")
        for r in rs:
            A(f"  - [{r.id}](#{_slug(r.id)}) - {r.applies_to}")
    A("")
    for title, rs in groups:
        A(f"## {title}")
        A("")
        A(BACK)
        A("")
        for r in rs:
            A(f"### {r.id}")
            A("")
            A(BACK)
            A("")
            A(f"**Applies to:** {r.applies_to} - checked at the `{r.stage}` stage")
            A("")
            A(f"**Requirement:** {r.requirement}")
            A("")
            A(f"**Severity:** `{r.severity}`"
              + ("" if r.severity == "error"
                 else " - advisory, does not block publishing"))
            A("")
            A(f"**Why:** {r.why}")
            A("")
            A("**You will see:**")
            A("")
            A("```text")
            A(_verified_example(r))
            A("```")
            A("")
    (GENERATED.parent / "LINTING_RULES.md").write_text(
        chr(10).join(L), encoding="utf-8", newline=""
    )


def main() -> None:
    # Count of individual (non-bundle) plugins for the summary line.
    individual_plugin_count = 0

    # Clear and recreate _generated/ (clean slate each run)
    if GENERATED.exists():
        shutil.rmtree(GENERATED)
    GENERATED.mkdir(parents=True)

    # ── Phase 1: emit each construct's plugin dir once ─────────────────────────
    # Claude Code owns the physical mirror; every platform's marketplace.json
    # points at these same dirs. ``build_plugin_json`` is platform-neutral, so
    # it is built once per plugin and reused when composing each platform's
    # entries. A construct absent from every platform's ``supports`` still emits
    # its dir but contributes no marketplace entry (e.g. F8: rules are a Claude
    # memory feature, not a plugin — see platforms.py supports docstrings).
    emitted: list[tuple] = []
    for construct in CONSTRUCTS.values():
        supported = any(
            type(construct) in p.supports for p in PLATFORMS.values()
        )
        for name in scan_source_dir(construct.source_directory):
            plugin_dir = GENERATED / f"{construct.prefix}-{name}"
            plugin_dir.mkdir(parents=True, exist_ok=True)
            construct.emit(name, plugin_dir)
            plugin_json = construct.build_plugin_json(name) if supported else None
            emitted.append((construct, plugin_dir, plugin_json))
            individual_plugin_count += 1

    # ── Phase 5: one top-level marketplace.json per platform ───────────────────
    # Each platform lists the plugins its ``supports`` set covers, then shapes
    # its own top-level manifest via ``marketplace_manifest``: Claude keeps a
    # top-level description and owner.url; OMP emits its documented native shape
    # (metadata.description, {name, email?} owner/author). Entries are sorted by
    # category then name for deterministic diffs; Claude Code's sorted entries
    # drive the catalog and summary below.
    marketplace_entries: list[dict] = []
    for platform in PLATFORMS.values():
        entries = _entries_for_platform(platform, emitted)
        entries.sort(key=lambda e: (e["category"], e["name"]))
        _write_marketplace_json(
            platform.marketplace_manifest(entries), platform.marketplace_json
        )
        if platform.name == "claude-code":
            marketplace_entries = entries

    # ── Phase 7: the generated catalog & installation doc (drift-checked) ──────
    _write_catalog(marketplace_entries)

    # ── Phase 8: the generated lint-rule list (drift-checked) ─────────────────
    _write_lint_rules_doc()

    # ── GENERATED-stage lint ──────────────────────────────────────────────────
    # These rules inspect emitted output, so this is the first moment they can
    # run at all — lint.py's CLI runs before the generator and would be
    # checking a stale tree. Same registry, same driver, later in the pipeline.
    from lint import run as run_lint
    from lint_rules import Stage

    generated_findings = run_lint(REPO_ROOT, {Stage.GENERATED})
    if generated_findings:
        for f in generated_findings:
            print(f"  FAIL: {f.message()}", file=sys.stderr)
        raise SystemExit(
            f"{len(generated_findings)} generated-output lint violation(s)"
        )

    # Summary
    from collections import Counter
    cats = Counter(e["category"] for e in marketplace_entries)
    print(f"Generated {len(marketplace_entries)} plugin entries in marketplace.json")
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")
    print(f"  {individual_plugin_count} individual plugins")


def _check_drift() -> int:
    """Snapshot current outputs, regenerate, diff. Return 0 if identical, 1 if drift.

    On drift the pre-check tree is RESTORED before returning, so --check is
    read-only from the caller's point of view and deterministic across runs.
    (Before this fix the check regenerated in place and left the new tree on
    disk, so a failing check silently "fixed" the drift and a rerun passed —
    three independent newcomer walkthroughs hit that fail-once-then-pass trap.)
    """

    def snapshot_tree(roots: list[Path]) -> dict[str, bytes]:
        out: dict[str, bytes] = {}
        for root in roots:
            if not root.exists():
                continue
            if root.is_file():
                # Individual file targets (the generated catalog doc).
                # rglob("*") yields nothing for a file, so these must be read directly.
                out[str(root.relative_to(REPO_ROOT))] = root.read_bytes()
                continue
            for p in sorted(root.rglob("*")):
                if p.is_file():
                    out[str(p.relative_to(REPO_ROOT))] = p.read_bytes()
        return out

    # Root-level generated files (no mirror dirs remain post scope-down)
    root_generated = [
        REPO_ROOT / "_generated" / "CATALOG_AND_INSTALLATION_INSTRUCTIONS.md",  # Phase 7
        REPO_ROOT / "_generated" / "LINTING_RULES.md",                          # Phase 8
    ]
    # Each platform's top-level manifest dir (.claude-plugin/, .omp-plugin/).
    manifest_dirs = [p.marketplace_json.parent for p in PLATFORMS.values()]
    targets = [GENERATED, *manifest_dirs] + root_generated

    before = snapshot_tree(targets)
    main()
    after = snapshot_tree(targets)

    if before == after:
        print("OK: generated content matches committed content.")
        return 0

    missing = sorted(set(before) - set(after))
    added = sorted(set(after) - set(before))
    changed = sorted(p for p in (set(before) & set(after)) if before[p] != after[p])

    # Restore the pre-check tree: delete files the regen added, rewrite
    # every file that existed before. Directories emptied by the deletes are
    # pruned so the tree is byte-identical to the pre-check state.
    for rel in added:
        (REPO_ROOT / rel).unlink(missing_ok=True)
    for rel, data in before.items():
        p = REPO_ROOT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
    for root in targets:
        if root.is_dir():
            for d in sorted(root.rglob("*"), reverse=True):
                if d.is_dir() and not any(d.iterdir()):
                    d.rmdir()

    print("DRIFT detected. Run `uv run scripts/generate_manifest.py` and commit the result.")
    print("(working tree restored to its pre-check state)")
    for p in missing:
        print(f"  removed:  {p}")
    for p in added:
        print(f"  added:    {p}")
    for p in changed:
        print(f"  changed:  {p}")
    return 1


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(_check_drift())
    main()
